name: pdf_editor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pdf: ^3.11.1
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  sqflite: ^2.4.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  share_plus: ^10.0.3
  flutter_lints: ^4.0.0
  flutter_pdfview: ^1.3.3
  pdfx: ^2.8.0
  device_info_plus: ^10.1.2
  signature: ^5.5.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.14.1
  open_file: ^3.5.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/wallpaper.jpg
    - assets/images/sydlogo.png
    - assets/documents/syd_servis_islem_formu.pdf
    - assets/documents/sydservisformu.pdf

  fonts:
    - family: Georgia
      fonts:
        - asset: assets/fonts/georgia.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/sydlogo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/sydlogo.png"
